#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidIntro.Resource", IsApplication=true)]

namespace AndroidIntro
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int aqua = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int blue = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int green = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int pink = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int red = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int yellow = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int lotus = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int btn_layoutDemo = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int btn_listDemo = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int demo_list_view = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int img_fill_image = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int myButton = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int random_color_view = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int red = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int view = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FrameLayoutDemo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LinearLayoutDemo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LinearLayoutWeightedDemo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListViewDemo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListViewItemDemo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PopQuiz = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RelativeLayoutDemo = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
